pull_request_template.md

[TFN-305] create pr template for pull requests

---

package-lock.json
package.json
src/data/auroradb.ts
src/pages/api/csvUpload.ts
src/pages/api/howManyProducts.ts
src/pages/api/periodValidity.ts
src/pages/direction.tsx
src/pages/howManyProducts.tsx
src/pages/matching.tsx
tests/pages/__snapshots__/howManyProducts.test.tsx.snap
tests/pages/api/periodValidity.test.ts
tests/testData/mockData.ts

- Redirect to correct page for one product
- some cleaning up of db types
- throw error if no stops in matching json
- Navigate to the howManyProducts page
- Enter 1
- You should be redirected to the periodProduct page
- Ensure all journeys are still working
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update
-   [x] Able to run pr locally
-   [ ] Lighthouse performed - N/A
-   [x] Followed acceptance criteria
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have made corresponding …

Redirect to correct page if one product

---

package-lock.json
package.json
src/data/auroradb.ts
src/pages/api/csvUpload.ts
src/pages/api/direction.ts
src/pages/api/howManyProducts.ts
src/pages/api/periodValidity.ts
src/pages/direction.tsx
src/pages/howManyProducts.tsx
src/pages/matching.tsx
src/utils/index.ts
tests/pages/__snapshots__/howManyProducts.test.tsx.snap
tests/pages/api/direction.test.ts
tests/pages/api/periodValidity.test.ts
tests/pages/direction.test.tsx
tests/testData/mockData.ts

Request to release into master/pre-prod the folllowing:
1) New feature that implements the logic to determine user journey based on whether service selected is a circular or non-circular journey.
2) Fix that ensures that the circular/non-circular logic is not applied when user has selected the single ticket journey.
3) Fix to ensure that when a user enters 1 as the number of products they are taken down the single product journey (as opposed to the multiple product journey).
Needs to be throughly smoke-tested when released to the pre-prod environmen
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This …

Request to release feature & fix in relation to circular/non-circular journeys and fix in relation to number of products page.

---

src/constants/index.ts
tests/layout/__snapshots__/AlphaBanner.test.tsx.snap
tests/pages/__snapshots__/thankyou.test.tsx.snap

-   Add IW email to feedback
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update
-   [x] Able to run pr locally
-   [ ] Lighthouse performed -N/A
-   [x] Followed acceptance criteria
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have made corresponding changes to the documentation if applicable -N/A
-   [x] I have added tests that prove my fix is effective or that my feature works

Updated feedback email addresses

---

src/constants/index.ts
src/design/Pages.scss
src/pages/api/matching.ts
src/pages/api/multipleProductValidity.ts
src/pages/api/periodValidity.ts
src/pages/api/singleOperator.ts
src/pages/matching.tsx
src/pages/multipleProductValidity.tsx
src/pages/singleOperator.tsx
tests/layout/__snapshots__/AlphaBanner.test.tsx.snap
tests/pages/__snapshots__/matching.test.tsx.snap
tests/pages/__snapshots__/multipleProductValidity.test.tsx.snap
tests/pages/__snapshots__/thankyou.test.tsx.snap
tests/pages/api/multipleProductValidity.test.ts
tests/pages/api/periodValidity.test.ts
tests/pages/api/singleOperator.test.ts
tests/pages/multipleProduct.test.tsx
tests/pages/multipleProductValidity.test.tsx
tests/testData/mockData.ts

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update
-   [ ] Able to run pr locally
-   [ ] Lighthouse performed
-   [ ] Followed acceptance criteria
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have made corresponding changes to the documentation if applicable
-   [ ] I have added tests that prove my fix is effective or that my feature works

Pre-prod release

---

pull_request_template.md

Update PR template to use full list of conventional commit types
-   [x] docs - Documentation only changes
-   [ ] revert - …

Updated PR template to include conventional commit types

---

src/pages/api/inboundMatching.ts
src/pages/api/matching.ts
tests/pages/_document.test.tsx
tests/pages/api/inboundMatching.test.ts
tests/pages/api/matching.test.ts
tests/testData/mockData.ts

fix: Amended matching fare zone types naming to be consistent

---

.circleci/config.yml
tests/pages/_document.test.tsx

-   Updating pipeline so it runs firefox and ie tests
-   Rerun pipeline on circleci for develop branch …

Updated config yml to run firefox and IE tests alongside chrome

---

.circleci/config.yml
.prettierrc.js

-   Run UI tests in BrowserStack
-   [x] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
-   [ …

Update CircleCI config to use BrowserStack scripts for UI tests

---

.circleci/config.yml
src/pages/api/register.ts
tests/pages/api/register.test.ts

Update build step in pipeline to use cognito env vars
-   [x] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
-   [ ] revert - Reverts a …

Set cognito env vars in pipeline

---

.circleci/config.yml
next.config.js
package.json
src/data/amplify.ts
src/pages/api/register.ts

Run Amplify auth configuration at runtime …

Configure Amplify auth at runtime

---

src/pages/multipleProductValidity.tsx
tests/pages/__snapshots__/multipleProductValidity.test.tsx.snap

-   The hint text was not useful on the multiple period validity page, so it has been updated to make users understand the page better.
-   Run the site through fdbt-dev repo and run through the period journey for multiple products, to get to the page.
-   [ ] ci - …

Added hint text to multiple validity page and updated some css

---

src/pages/api/resetPassword.ts
src/pages/resetPassword.tsx
tests/pages/api/resetPassword.test.ts

Fix for the expiry date when resetting password
-   [ ] chore - Other changes that don't modify src or …

fix for utc expiry link for reset password

---

src/pages/index.tsx
tests/pages/__snapshots__/index.test.tsx.snap

-   To update the content on the start page, to match what is on TFN-525 Jira ticket. Included ',' around the excludes rail text.
- Run the site locally through fdbt-dev repo. …

Updated content on start page and updated snapshot test

---

server/middleware/authentication.ts
src/pages/fareType.tsx

-   Set uuid on fareType page to ensure there is a new one for each journey
-   [ …

set uuid on fareType page

---

server/index.ts
src/pages/login.tsx
src/pages/requestAccess.tsx
tests/pages/__snapshots__/login.test.tsx.snap
tests/pages/__snapshots__/requestAccess.test.tsx.snap
tests/pages/requestAccess.test.tsx

-   Creating a request access page for users to get an account to use the site.
-   Run the site locally and hit /requestAccess manually, or use the link from the login page. …

Created request access page

---

server/index.ts
src/layout/Footer.tsx
src/pages/contactUs.tsx
tests/layout/__snapshots__/Footer.test.tsx.snap

Create the contact us page. Note I have used two thirds and one third build in classes rather than the build in two thirds component as it does not work if we utilise the component.
Browse to http://localhost:5555/contactUs. Also the footer link directs you to the page
-   [ ] build - Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, …

Creation of the contact us page

---

src/pages/fareType.tsx
tests/pages/faretype.test.tsx

-   The UUID was too long and not very user friendly, so we made it shorter and preprended it with the users NOC code.
-   Unit test added proves fix, can also see on thankyou page. …

Changed uuid to include NOC and only be 11 digits long

---

server/middleware/authentication.ts
src/utils/index.ts

-   Changing secure option for cookie setting to false, to see if it fixes the 500 internal error we're seeing on test site.
-   Use the test site. …

Changed secure to false for cookie setting

---

src/pages/register.tsx
tests/pages/__snapshots__/register.test.tsx.snap

fix issue with register page

---

src/components/MatchingList.tsx
tests/components/MatchingList.test.tsx
tests/components/__snapshots__/MatchingList.test.tsx.snap

-   This PR fixes the kebab casing of IDs in MatchingList.tsx
-   Pull down this branch and run the site locally. Run the UI tests against the site locally and check that they pass. …

Amended kebab casing on IDs in MatchingList.tsx

---

src/pages/api/stageNames.ts
src/pages/stageNames.tsx
tests/pages/__snapshots__/stageNames.test.tsx.snap
tests/pages/api/stageNames.test.ts
tests/pages/stageNames.test.tsx

-   To release the functionality that adds error summaries to the stage names page
-   Can be tested in the 'test' environment - tfn-test.infinityworks.com …

feat: added error summary component to stage names page

---

.circleci/config.yml

-   Update pipeline to deploy tags to prod
-   [x] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs) …

setup prod pipeline

---

server/middleware/sessions.ts
src/components/Breadcrumbs.tsx
src/data/cognito.ts
src/data/s3.ts
tests/components/__snapshots__/Breadcrumbs.test.tsx.snap

-   Set region for aws sdk commands
- …

fix: set region for aws sdk commands

---

src/data/auroradb.ts

For dev and testing we need to use our own noc code 'IWBusCo'
- run repo locally and can run through a journey and see if the WBTR data is being populated under pages such as services.
- Also can check if the unvalidated-dev bucket locally that the new netex has been created with but with the IWBusCo path
-   [ ] build - Changes that affect the build system or external dependencies …

updated to use IWBusCo

---

src/data/auroradb.ts
src/pages/api/register.ts
src/pages/matching.tsx
src/pages/resetConfirmation.tsx
src/utils/dataTransform.ts
tests/pages/__snapshots__/resetConfirmation.test.tsx.snap
tests/pages/api/register.test.ts

- Update reg process to check NOC against Cognito
- Allow IWBusCo NOC on reg page even though it is not in the DB
- Fixes ordering of stops on matching page
- Create user in Cognito using new cognito-manager script
- Putting in a different NOC that is in the DB on the reg page should fail
- Test that IWBusCo NOC works on reg page
-   [ ] build - Changes that affect the build system …

updated registration process to check NOC matches one in Cognito

---

src/constants/index.ts
src/interfaces/index.ts
src/pages/api/salesOfferPackages.ts
src/pages/salesOfferPackages.tsx
src/utils/breadcrumbs.ts
src/utils/sessions.ts
tests/pages/__snapshots__/salesOfferPackages.test.tsx.snap
tests/pages/api/salesOfferPackages.test.ts
tests/pages/salesOfferPackages.test.tsx
tests/testData/mockData.ts

- Jira ticket https://infinityworks.atlassian.net/browse/TFN-533
- Implement the sales offer package page
- If you run it locally and disableAuth
- Browse to http://localhost:5555/salesOfferPackages
-   [ ] ci - Changes to our CI configuration files and scripts …

Define sales offer package page

---

src/pages/api/csvUpload.ts
src/pages/api/csvZoneUpload.ts
src/pages/csvUpload.tsx
src/pages/csvZoneUpload.tsx
src/pages/howManyStages.tsx
tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap
tests/pages/__snapshots__/howManyStages.test.tsx.snap

Updated casing for any reference to "csv"
https://infinityworks.atlassian.net/browse/TFN-557
Go through to the howManyStages page and also the uploadCSV for both journeys
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, …

Updated casing for csv

---

src/pages/_document.tsx

Added google analytics 
can set the flag for the process to process.env.Stage !== 'prod' and add the following chrome extension
https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
When running any page you should see the google analytics within the console in development tools
-   [ ] build - Changes that affect the build system or …

Add script for google analytics

---

server/middleware/security.ts

-   Enable HSTS Preloading
-   [ ] …

enable hsts preloading

---

src/components/SalesOfferPackageExplanation.tsx
src/constants/index.ts
src/data/auroradb.ts
src/interfaces/index.ts
src/pages/api/describeSalesOfferPackage.ts
src/pages/api/priceEntry.ts
src/pages/api/salesOfferPackages.ts
src/pages/chooseValidity.tsx
src/pages/describeSalesOfferPackage.tsx
src/pages/multipleProductValidity.tsx
src/pages/multipleProducts.tsx
src/pages/productDetails.tsx
src/pages/salesOfferPackages.tsx
src/pages/service.tsx
src/pages/singleDirection.tsx
src/pages/stageNames.tsx
src/utils/breadcrumbs.ts
src/utils/sessions.ts
tests/components/SalesOfferPackageExplanation.test.tsx
tests/components/__snapshots__/SalesOfferPackageExplanation.test.tsx.snap
tests/pages/__snapshots__/describeSalesOfferPackage.test.tsx.snap
tests/pages/__snapshots__/salesOfferPackages.test.tsx.snap
tests/pages/api/describeSalesOfferPackage.test.ts
tests/pages/api/salesOfferPackages.test.ts
tests/pages/chooseValidity.test.tsx
tests/pages/describeSalesOfferPackage.test.tsx
tests/pages/multipleProduct.test.tsx
tests/pages/periodValidity.test.tsx
tests/pages/salesOfferPackages.test.tsx
tests/pages/service.test.tsx

-   This PR adds an extra page to the sales offer package user flow, which allows a user to provide a name and description for their sales offer package.
-   Pull down this branch and run the site locally. Validate that the new page works in conjunction with the other pages on the sales offer package user flow. Also validate that the page handles error cases as would be expected.
- …

feat: Added describeSalesOfferPackage page

---

src/pages/api/apiUtils/userData.ts
src/pages/api/howManyProducts.ts
src/utils/breadcrumbs.ts

-   Fix return circular journey
- Add breadcrumbs to select SoP page
-   [ ] …

fix circular return journey, add breadcrumbs to select SoP page

---

src/pages/api/apiUtils/userData.ts
src/pages/chooseValidity.tsx
tests/pages/__snapshots__/chooseValidity.test.tsx.snap

-   N/A
-   N/A
-   [ ] content - …

fix: period product sales offer package handling

---

src/components/InsetText.tsx
src/constants/index.ts
src/interfaces/index.ts
src/pages/api/apiUtils/userData.ts
src/pages/api/defineGroupPassengers.ts
src/pages/api/groupSize.ts
src/pages/defineGroupPassengers.tsx
src/pages/groupSize.tsx
src/pages/passengerType.tsx
src/utils/sessions.ts
tests/components/InsetText.test.tsx
tests/components/__snapshots__/InsetText.test.tsx.snap
tests/pages/__snapshots__/defineGroupPassengers.test.tsx.snap
tests/pages/__snapshots__/passengerType.test.tsx.snap
tests/pages/api/defineGroupPassengers.test.ts
tests/pages/api/groupSize.test.ts
tests/pages/defineGroupPassengers.test.tsx
tests/pages/groupSize.test.tsx

-   New page to create a group of passengers
-   Run the site through dev repo and manually navigate to /defineGroupPassengers
-   [ ] chore - …

feat: creating a group of different passenger types

---

src/constants/index.ts
src/pages/api/definePassengerType.ts
src/pages/api/passengerType.ts
src/pages/api/timeRestrictions.ts
src/pages/timeRestrictions.tsx
src/utils/sessions.ts
tests/pages/__snapshots__/timeRestrictions.test.tsx.snap
tests/pages/api/definePassengerType.test.ts
tests/pages/api/passengerType.test.ts
tests/pages/api/timeRestrictions.test.ts
tests/pages/timeRestrictions.test.tsx

-   To add a page which lets the user decide if there are time restrictions on their ticket or not.
-   Run site through dev repo and navigate through. …

feat: time restrictions start page

---

.eslintrc.js
src/interfaces/index.ts
src/pages/api/apiUtils/userData.ts
src/pages/api/definePassengerType.ts
src/pages/definePassengerType.tsx
tests/pages/__snapshots__/definePassengerType.test.tsx.snap
tests/pages/api/apiUtils/userData.test.ts
tests/pages/api/definePassengerType.test.ts
tests/pages/definePassengerType.test.tsx
tests/testData/mockData.ts

-   This PR fixes a few separate issues that have arisen as a consequence of recent releases to develop.
1.  Fixes matching json for both group and non-group tickets (introduced by TFN-610)
2. Fixes issue with site rendering the error page when time restrictions are undefined (introduced by TFN-634)
3. Fixes issue with definePassengerType page trying to validate attributes that don't exist (introduced by TFN-609)
-   Pull down this branch and run the site locally. Validate that the above issues have been fixed.
-   The `fdbt-ui-automation` repo has a branch (`fix/adults_no_proof`) which works with this PR. An easy way to generate matching json for each route through the site is to use this branch and run the UI tests against the site locally.
-   [X] fix - A …

fix: fixed matching json and other site issues

---

src/constants/index.ts
src/pages/api/definePassengerType.ts
src/pages/definePassengerType.tsx
tests/pages/api/definePassengerType.test.ts
tests/pages/definePassengerType.test.tsx
tests/testData/mockData.ts

-   This PR fixes the issues outlined in TFN-679 (https://infinityworks.atlassian.net/browse/TFN-679)
-   Pull down this branch and run the site locally. Validate that the site behaves as expected and that the issues outline in the above ticket are fixed.
-   [ ] ci - …

fix: amended definePassengerType page to use an errors cookie on errors

---

src/constants/index.ts
src/data/auroradb.ts
src/pages/api/register.ts
src/pages/fareType.tsx
src/pages/login.tsx
src/pages/thankyou.tsx
tests/pages/__snapshots__/login.test.tsx.snap
tests/pages/faretype.test.tsx

-   Do not log out 'transaction start' and 'transaction complete' messages for IWBusCo …

do not log transaction status logs if IWBusCo

---

src/pages/contact.tsx
tests/pages/__snapshots__/contact.test.tsx.snap

-   Add telephone number to contact page …

add telephone number to contact page

---

.circleci/config.yml
server/middleware/authentication.ts

-   Set NOC in cookie when disabling auth …

set noc when disabling auth

---

.circleci/config.yml
server/middleware/authentication.ts
src/constants/index.ts
src/interfaces/index.ts
src/pages/api/apiUtils/typeChecking.ts
src/pages/api/csvUpload.ts
src/pages/api/inputMethod.ts
src/pages/api/priceEntry.ts
src/pages/fareType.tsx
src/pages/inputMethod.tsx
src/utils/breadcrumbs.ts
src/utils/sessions.ts
tests/testData/mockData.ts
tests/utils/breadcrumbs.test.ts

Input method cookie to session attribute

---

src/constants/index.ts
src/pages/api/priceEntry.ts
src/pages/priceEntry.tsx
src/utils/sessions.ts
tests/pages/priceEntry.test.tsx

price entry cookies to one session attribute

---

src/constants/index.ts
src/interfaces/index.ts
src/pages/api/chooseValidity.ts
src/pages/api/periodValidity.ts
src/pages/chooseValidity.tsx
src/utils/sessions.ts
tests/pages/api/chooseValidity.test.ts
tests/testData/mockData.ts

-   To change days valid from a cookie to a session
-   [ ] chore - Other changes that don't modify src or …

Days valid cookie moved to session and tests updated

---

src/constants/index.ts
src/interfaces/index.ts
src/pages/api/apiUtils/typeChecking.ts
src/pages/api/apiUtils/userData.ts
src/pages/api/multipleProductValidity.ts
src/pages/api/outboundMatching.ts
src/pages/api/periodType.ts
src/pages/api/selectSalesOfferPackage.ts
src/pages/periodType.tsx
src/utils/breadcrumbs.ts
src/utils/sessions.ts
tests/testData/mockData.ts
tests/utils/breadcrumbs.test.ts

- Update period cookie to be in session
- Refactored session logic to prevent complex union type error and to only need single type map

Period type cookie

---

src/constants/index.ts
src/pages/api/apiUtils/typeChecking.ts
src/pages/api/stageNames.ts
src/pages/priceEntry.tsx
src/pages/stageNames.tsx
src/utils/sessions.ts
tests/pages/api/stageNames.test.ts
tests/pages/priceEntry.test.tsx
tests/testData/mockData.ts

-   To change the 2 stage name cookies to one stage name attribute stored in the session.
-   [ ] chore - …

Competed change and updated tests

---

src/components/Help.tsx
src/layout/Layout.tsx
tests/components/Help.test.tsx
tests/components/__snapshots__/Help.test.tsx.snap
tests/pages/contact.test.tsx

Add help and support to all the pages apart from contact https://infinityworks.atlassian.net/browse/TFN-624
Navigate through a journey and check to see if the help and support section is there.
It should appear on the contact us page …

Help text for all pages apart from contact

---

src/components/Help.tsx
src/pages/home.tsx
tests/components/__snapshots__/Help.test.tsx.snap
tests/pages/__snapshots__/home.test.tsx.snap

fix for spacing for home page

---

src/pages/confirmation.tsx
tests/pages/__snapshots__/confirmation.test.tsx.snap

-   This PR fixes an alignment issue on the MVP confirmation page.
-   Pull down this branch and run the site locally. Validate that the `confirmation` page is correctly aligned. …

Fixed alignment issue on confirmation page

---

src/components/ProductRow.tsx
src/pages/api/confirmation.ts
src/pages/api/multipleProducts.ts
src/pages/selectSalesOfferPackage.tsx
src/pages/thankyou.tsx
tests/pages/api/multipleProducts.test.ts
tests/testData/mockData.ts

-   Fix error on multi product journey …

fix product name issue

---

package-lock.json
package.json
src/pages/api/register.ts
tests/pages/api/register.test.ts

-   To make our new users passwords have to be stronger, by changing the logic on the register API.
-   Run site locally, and get a register link from AWS. …

Updated tests and completed functionality

---

package-lock.json
src/pages/api/apiUtils/index.ts
src/pages/api/changePassword.ts
src/pages/api/register.ts
src/pages/api/resetPassword.ts
src/pages/register.tsx
src/pages/returnValidity.tsx
tests/pages/__snapshots__/register.test.tsx.snap
tests/pages/__snapshots__/returnValidity.test.tsx.snap
tests/pages/api/apiUtils/index.test.ts
tests/pages/api/register.test.ts
tests/pages/api/resetPassword.test.ts
tests/pages/register.test.tsx

- Add weak password validation to change and reset password flows
- Added fieldset to return validity page …

Change password validation

---

src/design/Pages.scss
src/pages/cookieDetails.tsx

Cookie details page which is static
Browse to /cookieDetails page
-   [ ] revert …

add cookie details page

---

src/pages/ticketConfirmation.tsx
tests/pages/ticketConfirmation.test.tsx

When journey is non-circular the ticket confirmation page errors 
Go through a return non-circular journey and it should present the ticket confirmation page …

bug fix for confirmation page

---

server/middleware/authentication.ts
src/constants/index.ts
src/interfaces/index.ts
src/pages/api/cookies.ts
src/pages/api/productDateInformation.ts
src/pages/api/productDetails.ts
src/pages/api/salesConfirmation.ts
src/pages/ticketConfirmation.tsx
tests/pages/__snapshots__/ticketConfirmation.test.tsx.snap
tests/pages/api/cookies.test.ts
tests/pages/api/productDateInformation.test.ts
tests/pages/api/productDetails.test.ts
tests/pages/cookies.test.tsx
tests/pages/ticketConfirmation.test.tsx

-   To fix the bug around date inputs after the API was changed as part of the confirmation page work.
- …

fix: date input error correction

---

src/pages/_document.tsx

-   Anonymise IP in GA for GDPR purposes

anonymise ip in google analytics

---

src/pages/api/csvZoneUpload.ts
tests/pages/api/csvZoneUpload.test.ts

-   The multiple operators journey needs to reuse the csvZoneUpload page, and the API attached needs to redirect according to the fareType (if it is multi operator or not).
-   Unit test covers functionality.
-   [ ] ci - Changes to our CI configuration files and …

feat: incorporate csvZone page into multiple operators flow

---

src/pages/api/howManyProducts.ts
src/pages/howManyProducts.tsx
tests/pages/__snapshots__/howManyProducts.test.tsx.snap
tests/pages/api/howManyProducts.test.ts
tests/pages/howManyProducts.test.tsx

-   Changed the number of products page to change the content depending on the fareType. Also changed the max number of products to 5 instead of 10 (UI tests need to change).
-   Run locally and set fareType as multiOp (manually). …

Changed page content, changed tests, updated snapshots

---

server/index.ts

- add cookieDetails page to auth whitelist

add cookieDetails page to auth whitelist

---

src/pages/api/searchOperators.ts
src/pages/searchOperators.tsx
tests/pages/searchOperators.test.tsx

-   To stop operators seeing themselves in search results.
-   Attempt to search for the operator you are logged in as.
-   [ ] chore - Other …

Fixed issue and added comments to search operators page

---

src/pages/account.tsx
src/pages/api/multipleProductValidity.ts
src/pages/fareConfirmation.tsx
src/pages/forgotPassword.tsx
src/pages/resetLinkExpired.tsx
src/pages/ticketConfirmation.tsx
tests/pages/__snapshots__/account.test.tsx.snap
tests/pages/__snapshots__/forgotPassword.test.tsx.snap
tests/pages/__snapshots__/resetLinkExpired.test.tsx.snap
tests/pages/__snapshots__/ticketConfirmation.test.tsx.snap
tests/pages/api/multipleProductValidity.test.ts
tests/pages/ticketConfirmation.test.tsx

-   To address the DAC fixes we need to sort out ahead of DAC audit.
-   View pages and see issues fixed. …

DAC audit fixes and some routing fixes for period confirmation page

---

src/pages/defineTimeRestrictions.tsx
src/pages/login.tsx
src/pages/returnDirection.tsx
src/pages/thankyou.tsx
src/pages/ticketConfirmation.tsx
tests/pages/__snapshots__/defineTimeRestrictions.test.tsx.snap
tests/pages/__snapshots__/login.test.tsx.snap
tests/pages/__snapshots__/thankyou.test.tsx.snap
tests/pages/__snapshots__/ticketConfirmation.test.tsx.snap
tests/pages/ticketConfirmation.test.tsx
tests/testData/mockData.ts

-   A couple more tweaks for accessibility

a few more accessibility tweaks

---

src/pages/api/serviceList.ts
src/pages/serviceList.tsx
tests/pages/__snapshots__/serviceList.test.tsx.snap
tests/pages/api/serviceList.test.ts
tests/pages/serviceList.test.tsx

-   To ensure users have access to the multiple services side of multi operator period tickets.
-   Run site locally, and change server side props to navigate through pages as required, and ensure serviceList page behaves as expected. …

Changed page logic and text it renders

---

src/utils/index.ts

-   Fix error when logging out on thank you page
-   [ ] revert - Reverts a …

Fix bug when logging out on thank you page

---

src/constants/index.ts
src/data/auroradb.ts
src/interfaces/typeGuards.ts
src/pages/api/searchOperators.ts
src/pages/searchOperators.tsx
src/utils/sessions.ts
tests/pages/__snapshots__/searchOperators.test.tsx.snap
tests/pages/api/searchOperators.test.ts
tests/pages/searchOperators.test.tsx

-   This PR introduces the review and remove functionality to allow a user to remove any operators that they have previously searched for and then selected. 
-   Pull down this branch and run the site locally. Validate that the page behaves as expected in terms of all three of its components: (i) Search (ii) Add operators and (iii) Remove Operators.
-   Also validate that the page errors in the right way for each of the three components of functionality.
-   [ ] perf - A code change that improves …

feat: review and remove from selected operators

---

src/interfaces/index.ts
src/interfaces/typeGuards.ts
src/pages/api/apiUtils/userData.ts
src/pages/api/productDateInformation.ts
src/pages/api/salesConfirmation.ts
src/pages/productDateInformation.tsx
src/pages/salesConfirmation.tsx
src/pages/selectSalesOfferPackage.tsx
src/utils/sessions.ts
tests/pages/__snapshots__/ticketConfirmation.test.tsx.snap
tests/pages/api/apiUtils/userData.test.ts
tests/pages/api/productDetails.test.ts
tests/pages/api/searchOperators.test.ts
tests/pages/createdFiles.test.tsx
tests/pages/selectSalesOfferPackage.test.tsx
tests/pages/ticketConfirmation.test.tsx
tests/testData/mockData.ts

-   This PR adds the data collected from the user about multi operator geoZone tickets.
-   Pull down this branch and run the site locally. Validate that the matching json produced at the end of the multi operator, geoZone ticket flow is the correct format (check this against the mock data in the fdbt-dev repo).
-   Validate that the other ticket flows still produce matching json. …

feat: added matching json for multiOperatorGeoZone

---

src/pages/csvUpload.tsx
src/pages/csvZoneUpload.tsx
src/pages/passengerType.tsx
src/pages/returnDirection.tsx
src/pages/service.tsx
src/pages/singleDirection.tsx
tests/pages/__snapshots__/passengerType.test.tsx.snap
tests/pages/__snapshots__/returnDirection.test.tsx.snap
tests/pages/__snapshots__/service.test.tsx.snap
tests/pages/__snapshots__/singleDirection.test.tsx.snap

-   This PR improves the help text on a number of pages to assist with identified user pain points on the service.
-   Pull down this branch and run the site locally. Check that the content improvements on the ticket are reflected in the PR.
-   [ ] ci - Changes to …

feat: help text content improvements

---

package-lock.json
package.json
src/constants/index.ts
src/design/Layout.scss
src/interfaces/index.ts
src/interfaces/typeGuards.ts
src/pages/api/multipleOperatorsServiceList.ts
src/pages/csvUpload.tsx
src/pages/csvZoneUpload.tsx
src/pages/multipleOperatorsServiceList.tsx
src/pages/passengerType.tsx
src/pages/returnDirection.tsx
src/pages/searchOperators.tsx
src/pages/service.tsx
src/pages/singleDirection.tsx
src/pages/ticketRepresentation.tsx
src/utils/sessions.ts
tests/pages/__snapshots__/multipleOperatorsServiceList.test.tsx.snap
tests/pages/__snapshots__/passengerType.test.tsx.snap
tests/pages/__snapshots__/returnDirection.test.tsx.snap
tests/pages/__snapshots__/service.test.tsx.snap
tests/pages/__snapshots__/singleDirection.test.tsx.snap
tests/pages/__snapshots__/ticketRepresentation.test.tsx.snap
tests/pages/api/multipleOperatorsServiceList.test.ts
tests/pages/api/serviceList.test.ts
tests/pages/multipleOperatorsServiceList.test.tsx

fix: address text overlap on magnification on smaller screens
feat: select services for additional operators
fix: dependency vulnerabilities
feat: Content improvements for user pain points

PreProd Release

---

src/interfaces/index.ts
src/pages/api/apiUtils/userData.ts
src/pages/api/salesConfirmation.ts
src/pages/searchOperators.tsx
tests/pages/__snapshots__/searchOperators.test.tsx.snap
tests/pages/api/apiUtils/userData.test.ts
tests/testData/mockData.ts

-   To allow users to create matching JSON for multi service multi operator tickets, and then create netex with that.
-   Use site locally to create matching JSON, download it and see it is in the structure we want it to be in. …

Display NOC codes alongside operator names on search Page, and Matching Json updates

---

server/index.ts
src/layout/Footer.tsx
src/pages/accessibility.tsx
tests/layout/__snapshots__/Footer.test.tsx.snap

Accessibility page 
- Browse to /accessibility
- Also link in the footer
- Should be accessible if not authenticated
-   [ ] chore - Other changes …

accessibility page

---

src/pages/groupPassengerTypes.tsx
tests/pages/__snapshots__/groupPassengerTypes.test.tsx.snap

Content change for the group passenger type page
Browse to the http://localhost:5555/groupPassengerTypes …

changed help text on the group passenger page

---

src/pages/inputMethod.tsx
tests/pages/__snapshots__/csvUpload.test.tsx.snap
tests/pages/__snapshots__/inputMethod.test.tsx.snap

-   To explain to the user what a CSV is.
-   View page.
-   [ ] revert - Reverts …

Added csv explanation

---

src/pages/howManyProducts.tsx
tests/pages/__snapshots__/howManyProducts.test.tsx.snap
tests/pages/howManyProducts.test.tsx

-   This PR amends the heading on the howManyProducts page. The heading now takes consideration of both the ticket type (i.e. geoZone or selectedServices) and fare type (i.e period or multiOperator).
-   Pull down this branch and run the site locally. Validate that the howManyProducts page heading is correct on each of the different user journeys.
-   [ ] build - Changes that …

content: updated howManyProducts page heading

---

src/data/auroradb.ts

Service needs to be ordered in ascending numerical order
Browse to http://localhost:5555/service which will have the services listed
You can force the query to change in the code base
const queryResults = await executeQuery<ServiceType[]>(queryInput, [nocCodeParameter]);
change the nocCodeParameter to any of the following like so ['MCTR']
BLAC
DCCL
ERDG
HCTY
MCTR
MCTR2
MCTR3
NWBT
PBLT
TLCT
VISB
WBTR
-   [ ] test - Adding missing tests or …

add order to service list

---

src/layout/Header.tsx
src/pages/home.tsx
src/pages/index.tsx
tests/layout/__snapshots__/Header.test.tsx.snap
tests/pages/__snapshots__/home.test.tsx.snap
tests/pages/__snapshots__/index.test.tsx.snap

-   To update capitalization as desired.
-   View pages.
-   [ ] revert - Reverts …

Updated capitalization

---

src/pages/searchOperators.tsx
tests/pages/__snapshots__/searchOperators.test.tsx.snap

-   So the user can hit enter to use each part of the forms on search operator page.
-   Use search operator page with tapping enter on 3 separate forms. …

Fixed enter key issue and content

---

src/design/Layout.scss

- Fix styling of cookies accepted banner …

fix cookies accepted banner styling

---

src/pages/csvUpload.tsx

-   To fix file size from 1.3 mb to 1.2 …

File size adjusted

---

src/pages/api/definePassengerType.ts
src/pages/api/fareType.ts
src/pages/definePassengerType.tsx
src/pages/fareType.tsx
tests/pages/__snapshots__/faretype.test.tsx.snap
tests/pages/api/definePassengerType.test.ts
tests/pages/api/faretype.test.ts

-   This PR adds a new option for a 'School Service' ticket to the `/fareType` page (currently as a disabled radio button).
-   This PR also adds some conditional routing if the user has selected this new option.
-   Pull down this branch and run the site locally. Validate that all AC on the ticket are satisfied.
-   [ ] build - Changes that affect the build system or external …

feat: added school service ticket option

---

src/pages/api/login.ts

-   Fix issue stopping users with multiple NOCs from logging in
-   [ ] revert - …

fix: users with multiple NOCs can login

---

src/pages/_app.tsx
src/pages/_document.tsx
src/pages/createdFiles.tsx
tests/pages/__snapshots__/_document.test.tsx.snap
tests/pages/__snapshots__/createdFiles.test.tsx.snap

-   Run gov js init after render to fix accordions
-   [ ] revert - Reverts a …

run init after render

---

src/pages/salesOfferPackages.tsx
tests/pages/__snapshots__/salesOfferPackages.test.tsx.snap

-   This PR adds `directDebit` and `cheque` to the payment method enumerations on the `/salesOfferPackage` page.
-   Pull down this branch and run the site locally. Validate that the new payment method enumerations are present on the `/salesOfferPackage` page and that they can be selected.
-   [ ] build - Changes that affect the build system or external dependencies (example …

feat: new SOP paymentMethod enumerations to facilitate school services

---

src/pages/api/howManyProducts.ts
src/pages/howManyProducts.tsx
tests/pages/__snapshots__/howManyProducts.test.tsx.snap
tests/pages/api/howManyProducts.test.ts

-   To allow users to create 10 products at once.
-   Use site, and observe 10 products can be created at once.
-   [ ] chore - Other changes that …

Increased number of products allowed from 5 to 10

---

src/interfaces/index.ts
src/pages/api/apiUtils/userData.ts
tests/pages/api/apiUtils/userData.test.ts
tests/testData/mockData.ts

-   To add termTime to the three ticket types allowed for a school service ticket, to the matching JSON.
-   Unit test coverage and alterations to generated netex prove that it adds the boolean and key as needed on 3 ticket types. …

School service matching json changes

---

src/pages/api/apiUtils/userData.ts
src/pages/salesOfferPackages.tsx
tests/pages/__snapshots__/salesOfferPackages.test.tsx.snap
tests/pages/salesOfferPackages.test.tsx

-   To allow the user to add more options for their sales offer packages.
-   Use site and observe new options.
-   [x ] feat - A new feature
-   [ ] chore - Other changes that …

feat: added more SOP enumerations

---

src/pages/api/feedback.ts
tests/pages/api/feedback.test.ts

-   The inputs on the page changed, but the API didnt.
-   Observe tests have changed and still pass. …

fix: Fixed API to correlate to inputs properly

---

src/constants/index.ts
src/pages/api/apiUtils/feedbackEmailer.ts
src/pages/api/feedback.ts
src/pages/feedback.tsx
tests/pages/__snapshots__/feedback.test.tsx.snap
tests/pages/api/apiUtils/feedbackEmailer.test.ts

-   To change the feedback content and make it easier to see where the emails come from.
-   Run locally. …

fix: Content changes and email changes

---

Dockerfile
src/pages/api/apiUtils/fileUpload.ts
start_clamav.sh
supervisord.conf

-   Add supervisor to manage site, clamd and freshclam
-   [ ] revert - Reverts a …

added supervisor to manage site, clamd and freshclam

---

src/pages/howManyProducts.tsx
src/pages/ticketConfirmation.tsx
tests/pages/__snapshots__/howManyProducts.test.tsx.snap
tests/pages/howManyProducts.test.tsx
tests/pages/ticketConfirmation.test.tsx

-   This PR adds the info collected during multiOp user journeys to the ticketConfirmation page so that the user can easily review the details they have provided.
-   Pull down this branch and run the site locally. Run through the following user journeys and check that the correct details are shown on the ticketConfirmation page:
1. period geoZone
2. period multiService
3. multiOp geoZone
4. multiOp multiService
5. schemeOp (forced down the multiOp geoZone route)
-   [ ] perf - A code change that …

feat: multi operator details on confirmation pages

---

src/components/ProductRow.tsx
src/pages/api/chooseValidity.ts
src/pages/chooseValidity.tsx
tests/pages/__snapshots__/chooseValidity.test.tsx.snap
tests/pages/api/chooseValidity.test.ts

-   Allow users to select hours for period validity dropdown list.
-   Use site and see new option in dropdown. Reflected in matching JSON.
-   [ ] …

feat: Allow users to select hours for period validity

---

src/layout/Footer.tsx
src/pages/privacy.tsx
tests/layout/__snapshots__/Footer.test.tsx.snap
tests/pages/__snapshots__/privacy.test.tsx.snap
tests/pages/privacy.test.tsx

-   To create a new static content privacy policy page.
-   Run site locally and see in footer.
-   [ ] chore - Other changes that don't modify src …

Completed privacy notice

---

next.config.js

-   This PR fixes an issue on test with the client render not having access to the required env vars. …

fix: added env vars to next.config

---

next.config.js
src/constants/index.ts
src/pages/contact.tsx
tests/pages/contact.test.tsx

-   Retrieve env vars in getServerSideProps so they are always available
-   [ ] …

retrieve env vars in getServerSideProps

---

src/pages/api/selectSalesOfferPackage.ts
tests/pages/api/selectSalesOfferPackage.test.ts

-   To make sure there is test coverage for the selectSalesOfferPackage API.
-   npm run test
-   [ ] chore - Other changes that don't modify src …

test: Created tests for selectSalesOfferPackage API

---

src/pages/api/salesConfirmation.ts
tests/pages/api/salesConfirmation.test.ts

-   To increase test coverage for missing tests on API's.
-   Run unit tests locally. …

test: Completed unit tests for sales confirmation API

---

src/pages/api/salesConfirmation.ts
tests/pages/api/salesConfirmation.test.ts

-   To fix issue created in API.
-   [ ] …

fix: remove check in API

---

src/pages/api/apiUtils/feedbackEmailer.ts

fix: updated feedback email destination

---

error/error/index.html

-   This PR updates the support email address and phone number on the static error page.
-   [ ] chore - Other changes that don't modify src or …

content: updated support contact info on static error page

---

supervisord.conf

-   tweaked supervisor logging config

tweaked supervisor logging config

---

src/interfaces/index.ts
src/pages/api/chooseTimeRestrictions.ts
src/pages/chooseTimeRestrictions.tsx
src/pages/resetPassword.tsx
src/pages/salesConfirmation.tsx
tests/pages/__snapshots__/chooseStages.test.tsx.snap
tests/pages/__snapshots__/feedback.test.tsx.snap
tests/pages/__snapshots__/multipleOperators.test.tsx.snap
tests/pages/__snapshots__/register.test.tsx.snap
tests/pages/__snapshots__/resetPassword.test.tsx.snap
tests/pages/__snapshots__/returnDirection.test.tsx.snap
tests/pages/__snapshots__/singleDirection.test.tsx.snap
tests/pages/api/chooseTimeRestrictions.test.ts
tests/pages/api/inputMethod.test.ts
tests/pages/chooseStages.test.tsx
tests/pages/chooseTimeRestrictions.test.tsx
tests/pages/chooseValidity.test.tsx
tests/pages/feedback.test.tsx
tests/pages/multipleOperators.test.tsx
tests/pages/register.test.tsx
tests/pages/resetPassword.test.tsx
tests/pages/returnDirection.test.tsx
tests/pages/salesConfirmation.test.tsx
tests/pages/singleDirection.test.tsx

-   This PR improves testing coverage on the site.
-   Pull down this branch and run the site locally. Check that the new tests are valid and that they increase coverage.
-   [X] test - Adding missing tests or correcting existing tests
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, …

test: improve testing coverage

---

package-lock.json
package.json

-   To fix the audit issue.
-  n/a
- …

fix: Fixed audit issue

---

src/pages/salesConfirmation.tsx

-   Redirect to home when hitting the salesConfimation page without necessary data
-   Complete journey and get to thank you page, click back, you should be taken to the homepage …

redirect to home when hitting the salesConfimation page without necessary data

---

src/pages/createdFiles.tsx
tests/pages/__snapshots__/createdFiles.test.tsx.snap

-   add home button to createdFiles page …

add home button to createdFiles page

---

src/pages/api/chooseTimeRestrictions.ts
src/pages/chooseTimeRestrictions.tsx
tests/pages/__snapshots__/chooseTimeRestrictions.test.tsx.snap
tests/pages/api/chooseTimeRestrictions.test.ts

-   altered wording on time restrictions 24hr from 2400.
-   n/a
-   [ ] revert - …

content: altered wording on time restrictions 24hr

---

src/components/TimeRestrictionsTable.tsx
src/pages/createdFiles.tsx
src/pages/definePassengerType.tsx
src/pages/fareConfirmation.tsx
src/pages/salesOfferPackages.tsx
src/pages/selectSalesOfferPackage.tsx
src/pages/ticketConfirmation.tsx
src/utils/index.ts
tests/pages/__snapshots__/createdFiles.test.tsx.snap
tests/pages/__snapshots__/fareConfirmation.test.tsx.snap
tests/pages/__snapshots__/salesOfferPackages.test.tsx.snap
tests/pages/fareConfirmation.test.tsx
tests/utils/index.test.ts

-   To edit the content to the fare confirmation page, and also include the concept of groups.
-  Run locally and use site through some different user type combinations (groups, nongroup etc).
-   [] fix - A bug fix
-   [ ] ci - Changes to our CI configuration files and scripts (example …

feat: Fare Confirmation page rework

---

package-lock.json
src/data/auroradb.ts

-   Update site to use new txc tables
-   Test pages that use DB queries still work correctly
-   [ ] chore - Other changes that don't modify src …

update aurora functions to use txc tables

---

src/components/DeleteSOPButton.tsx
src/components/SalesOfferPackageExplanation.tsx
src/data/auroradb.ts
src/interfaces/index.ts
src/pages/api/deleteSop.ts
src/pages/api/describeSalesOfferPackage.ts
src/pages/selectSalesOfferPackage.tsx
tests/components/DeleteSOPButton.test.tsx
tests/components/__snapshots__/DeleteSOPButton.test.tsx.snap
tests/components/__snapshots__/SalesOfferPackageExplanation.test.tsx.snap
tests/pages/api/describeSalesOfferPackage.test.ts

-   To allow the users to delete SOP's and also to stop them creating SOP's with the same names.
-   Run locally alongside new AWS repo branch and try deleting and creating new SOPs. …

feat: Allow users to delete SOPs

---

.circleci/config.yml

-   Update circleci orb versions
-   [x] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
-   [ ] …

update circleci orb versions

---

src/pages/fareConfirmation.tsx

-   Making proof / age range change links not appear for passenger type anybody 
-   Run locally and test. …

fix: Altered change links to not appear if passenger type is anybody

---

src/pages/multipleOperatorsServiceList.tsx
src/pages/serviceList.tsx
tests/pages/__snapshots__/multipleOperatorsServiceList.test.tsx.snap
tests/pages/multipleOperatorsServiceList.test.tsx

-   Adds in missing oirigin destination to BODS multi op service list
-   Check origin and destination displayed correctly
-   [ ] chore - Other …

fix: add missed origin destination for multioperator

---

cypress_tests/cypress/fixtures/example.json
cypress_tests/cypress/fixtures/fareTriangle.csv
cypress_tests/cypress/integration/flatFareSpec.ts
cypress_tests/cypress/integration/singleSpec.ts
cypress_tests/cypress/support/helpers.ts
cypress_tests/cypress/support/steps.ts
cypress_tests/package-lock.json
cypress_tests/package.json
cypress_tests/tsconfig.json

-   The UI test for cypress for the single ticket csv upload journey, end to end.
-   Run the site locally and use README in cypress directory for how to run cypress tests. npm i in the cypress directory will be needed also. …

test: cypress csv upload single

---

package-lock.json
package.json
tests/pages/_document.test.tsx
tsconfig.json

-   Updates nextjs to 10.1.3 in order to fix a vulnerability. No functional change.
-   Clear your browser's cache, then spin up the environment and test that you can run through a full journey.
-   [ ] ci - Changes to our CI configuration files and scripts (example …

next updated to v10

---

cypress_tests/cypress/integration/singleSpec.ts
cypress_tests/cypress/support/steps.ts

-   Implements the single manual upload ui test
-   Run the singleSpec cypress test …

test: single manual upload passing

---

cypress_tests/cypress/integration/returnSpec.ts
cypress_tests/cypress/support/steps.ts

-   Implements the return ticket csv upload and manual entry journey UI tests
-   Run the returnSpec cypress tests
-   [ ] chore - Other changes …

test: return ticket csv upload and manual

---

src/pages/api/apiUtils/index.ts
src/pages/api/defineTimeRestrictions.ts
src/pages/defineTimeRestrictions.tsx
tests/pages/api/defineTimeRestrictions.test.ts
tests/pages/defineTimeRestrictions.test.tsx
tests/testData/mockData.ts

fix: cfd 248 noc code bug

---

src/data/auroradb.ts
src/pages/api/chooseTimeRestrictions.ts
src/pages/api/definePassengerType.ts
tests/pages/api/definePassengerType.test.ts

-   Save the passenger types to the db
-   Go through the passenger type journey and check it gets saved in the DB
-   Go through again with the same passenger category (adult/child) but change a parameter
-   Check that the existing entry gets updated
-   [ ] ci - …

feature: CFD-242 Save passenger types

---

cypress_tests/cypress/support/helpers.ts
src/data/auroradb.ts
src/pages/api/definePassengerType.ts
src/pages/api/passengerType.ts
tests/pages/_document.test.tsx
tests/pages/api/passengerType.test.ts

-   The stored passenger type will be used instead of having to refill the details
-  Go through the passenger types flow to save a type to the DB
-  Do the Journey again and check the saved on is used and you skip straight to the time restrictions
-   [ ] ci - …

feat: CFD-243 - Use stored passenger types

---

src/data/auroradb.ts
src/interfaces/index.ts
src/pages/api/definePassengerType.ts
src/pages/api/passengerType.ts
src/pages/definePassengerType.tsx
tests/pages/api/definePassengerType.test.ts
tests/pages/api/passengerType.test.ts
tests/pages/definePassengerType.test.tsx

-   Save group passenger config in the DB
-   Create a group passenger type and name it
-   Check it saves in the DB
-   Create a group without a name and check it doesn't save …

feat: CFD-244 Save group passenger configs

---

cypress_tests/cypress/support/helpers.ts

Added code to handle pages when re-using data
Run in cy
-   [ ] revert - Reverts …

add url filtering

---

src/pages/fareType.tsx
tests/pages/__snapshots__/fareType.test.tsx.snap
tests/pages/fareType.test.tsx

removes carnet fartype selection from prod

fix: remove carnet fartype selection from prod

---

src/data/auroradb.ts

fix: retrieve name from db

---

src/pages/api/passengerType.ts
tests/pages/api/passengerType.test.ts

-   Fix broken change links for reused groups
-   See ticket for bug replication  …

fix: CFD-271 Fix broken change links for reused groups
