src/pages/api/fareType.ts
src/pages/fareType.tsx
tests/pages/__snapshots__/faretype.test.tsx.snap
tests/pages/api/faretype.test.ts

Linked to ticket https://infinityworks.atlassian.net/browse/TFN-375
Minor changes where we are enabling return type and changing the title of it. Also links to the service page.
With the lighthouse testing i have noticed performance is low around 40 which is the same in dev. So potentially need to think about a later ticket to get this sorted
Run locally and go through the journey until you get to the faretype page.  The return -single operator option will be enabled and present.
The error messaging is already in place so no changes required here.
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This …

[tfn-375] enable return single service faretype

---

src/pages/api/direction.ts
src/pages/selectJourneyDirection.tsx
tests/pages/api/direction.test.ts

When going through return single journey it should redirect automatically the inputmethod page if the journey is circular.
Test for circular
Run the web application
Select 'Warrington' bus operator
Service page and select the 'Return - Single Service'.
This should redirect to the /inputMethod as they only have a circular service, i.e. one service
Testing for non-circular
Non circular journey
Run web application
Select durham operator
Select any service and continue
On directions page select one option from the dropdown and continue
Will redirect to new page (NOT implemented) /journeySelection
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing …

Fix issue with circular journey auto redirect

---

src/pages/error.tsx

Add error page back in
-   Navigate to /error, it should show the error page rather than page not found …

fix: add error page back in

---

package.json
server/middleware/authentication.ts

-   Update npm start script to correctly point at the server index when running in docker
-   [ ] chore - Other changes that don't modify src or …

fix path to server index in start script

---

server/index.ts

-   Fix paths to static folders when running in docker
-  Scripts and fonts should load …

set correct path to static scripts and next folders

---

src/pages/api/passengerType.ts
tests/pages/api/passengerType.test.ts

-   This PR fixes the previous changes to site which broke the redirect functionality on the passengerType page. The passengerType page should always 'redirectOnFareType' when the user selects 'Anyone'.
-   Pull down this branch and run the site locally.
-   Check that the passengerType page uses the 'redirectOnFareType' functionality when you select 'Anyone' and that the page redirects to 'definePassengerType' when any other selection is made. …

Fixed redirection when passengerType is 'Anyone'

---

src/pages/api/definePassengerType.ts
tests/pages/api/definePassengerType.test.ts

-   This PR addresses the issue raised in TFN-558. Formatting has been added to the 'filteredReqBody' in the definePassengerType API to force the proof documents to always be passed through into the cookies and matching data as an array, even if the user only selects one proof document.
-   Pull down this branch and run the site locally.
-   Navigate through the definePassengerType page, select/enter different variations of data and validate that the proof documents are always passed into the cookies as an array.
-   [ ] refactor - A code change that neither fixes a bug nor …

fix: Force proof documents to always be an array

---

src/layout/Header.tsx
src/pages/account.tsx
src/pages/api/login.ts
src/pages/home.tsx
src/pages/index.tsx
src/pages/thankyou.tsx
src/utils/breadcrumbs.ts
tests/layout/Header.test.tsx
tests/layout/__snapshots__/Header.test.tsx.snap
tests/pages/__snapshots__/account.test.tsx.snap
tests/pages/__snapshots__/home.test.tsx.snap
tests/pages/__snapshots__/thankyou.test.tsx.snap
tests/pages/api/login.test.ts
tests/pages/home.test.tsx
tests/testData/mockData.ts

New landing page when logging in. I have renamed the current home page to start as it makes sense for the logged in journey to have the home.
-  Login into the site and it should redirect to the new home page. 
-  Check links work …

add home page after login

---

src/pages/selectSalesOfferPackage.tsx
tests/pages/__snapshots__/selectSalesOfferPackage.test.tsx.snap
tests/pages/selectSalesOfferPackage.test.tsx

-   This PR removes excess commas found in the predefined sales offer packages we offer to a user. These commas were causing the generated NeTEx to fail validation
-   Pull down this branch and run the site locally. Run through a user journey on the site and validate that the purchaseLocations within each sales offer package of the matching json do not contain excess commas.
-   [ …

fix: removed excess commas from predefined SOPs

---

src/pages/selectSalesOfferPackage.tsx
tests/pages/__snapshots__/selectSalesOfferPackage.test.tsx.snap

-   When the generate checkboxes method was running, if there was only a single product then there was no index being passed to the method, as it was optional. This meant that for a single product, the id's were including 'undefined' in them, which is not ideal and also makes the UI tests not work.
-   Run site locally, go to single product SOP page, and observe id's are correct.
- …

fix: hardcode index to zero for single products in the SOP page

---

package-lock.json
src/constants/index.ts
src/pages/api/definePassengerType.ts
src/pages/definePassengerType.tsx
tests/pages/definePassengerType.test.tsx
tests/testData/mockData.ts

For infant and adult in group passenger types the proof option is not required when defining the passengers.
- Select a faretype
- Once submitted change the url to http://localhost:5555/groupPassengerTypes
- Select adult, infant and continue
- for adult and infant the options should not show for proof
- Try the above again but select child and adult and the child should see the proof option
-   [ ] test - Adding missing tests or correcting …

Remove proof for adult and infant in group passenger types

---

src/pages/api/csvUpload.ts
tests/pages/api/csvUpload.test.ts
tests/testData/csvFareTriangleData.ts

-  Users were creating invalid Netex because the site allowed them to upload CSV's with duplicate fare stage names. This fix prevents that.
-   Run site through dev repo and attempt to upload a csv with duplicate fare stage names. …

fix: CSV duplicate fare stage names 

---

Dockerfile
README.md
src/pages/api/apiUtils/fileUpload.ts

-   Enable ClamAV to run on Fargate
- …

enable virus scanning to work on Fargate

---

src/design/Layout.scss

-   Prevent overlapping in header when zoomed on smaller screens
-   Magnify to 400% and shrink screen to 1280px, no text should overlap in the header, or any other part of the page …

address text overlap on magnification on smaller screens

---

src/pages/searchOperators.tsx
tests/pages/__snapshots__/searchOperators.test.tsx.snap

-   This PR adds hint text to the search operators page to explain to a user what a noc code is.
-   Pull down this branch and run the site locally. Check that the extra help text is present on the search operators page and that it reads correctly.
-   [ ] ci - …

feat: added hint text to search operators page

---

src/data/auroradb.ts
src/pages/priceEntry.tsx
tests/pages/__snapshots__/priceEntry.test.tsx.snap

- Remove fares triangle table roles to improve navigation for screen readers
- Swap internal NOC when doing operator search to return results
-   [ …

remove fares triangle table roles, fix operator search for internal NOC

---

src/layout/Header.tsx
src/pages/definePassengerType.tsx
tests/layout/__snapshots__/Header.test.tsx.snap
tests/pages/definePassengerType.test.tsx
tests/testData/mockData.ts

-   To ensure adults arent asked for proof documents when user is selecting user type.
-   Run site locally and check user pages, for group and non group. …

Changed page so that proof doesnt render for adults

---

src/pages/api/stageNames.ts
src/pages/stageNames.tsx
tests/pages/__snapshots__/stageNames.test.tsx.snap
tests/pages/api/stageNames.test.ts

-   To allow users enter longer fare stage names, up to 70 characters.
-   Use site and add longer fare stage names.
-   [ ] chore - Other changes …

Updated max number of characters for fare stage names

---

src/pages/api/definePassengerType.ts
tests/pages/api/definePassengerType.test.ts

-   Fix appending of passenger types that have already been defined
- Test both the group and single passenger type journeys
- Test going backwards and forwards between group passenger definition pages, passengers should not be appended indefinitely in the matching json / session
-   [ ] build - Changes that affect the build system or external dependencies (example scopes: gulp, …

fix appending of passenger types that have already been defined

---

src/constants/index.ts
src/design/Layout.scss
src/interfaces/index.ts
src/pages/api/chooseValidity.ts
src/pages/api/periodValidity.ts
src/pages/chooseValidity.tsx
src/utils/sessions.ts
tests/pages/__snapshots__/chooseValidity.test.tsx.snap
tests/pages/api/chooseValidity.test.ts
tests/pages/api/periodValidity.test.ts
tests/pages/api/productDateInformation.test.ts
tests/pages/chooseValidity.test.tsx
tests/testData/mockData.ts

-   To allow the user to say their product lasts for 3 weeks or 2 months etc, instead of just using days.
-   Run site locally, and progress to single product period page.
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, …

Altered single product page to take a number and type of duration

---

src/pages/ticketConfirmation.tsx

-   We were saying the users product duration was 3 weeks days or 4 days days. This is to lop off the last 'days'.
-   Use site to create a single product period ticket, and observe on ticketConfirmation page.
-   [ ] ci - Changes to our CI configuration files and …

Fixed confirmation page so it doesnt say days  on end of duration

---

src/pages/api/apiUtils/userData.ts
tests/pages/api/apiUtils/userData.test.ts

-   This PR ensures that the matching json produced for a school ticket contains a 'type' attribute which matches the actual ticket type (rather than `type = 'schoolService')`.
-   Pull down this branch and run the site locally. Validate that the type attribute is representative of the actual ticket type for each school service ticket type. 
-   [ ] build - Changes that affect the …

fix: replace fareType with schoolFareType for school services

---

package-lock.json
package.json
src/components/UserDataUploads.tsx
src/constants/index.ts
src/pages/api/apiUtils/fileUpload.ts
src/pages/api/csvZoneUpload.ts
src/pages/csvUpload.tsx
src/pages/csvZoneUpload.tsx
src/pages/inputMethod.tsx
tests/pages/__snapshots__/csvUpload.test.tsx.snap
tests/pages/__snapshots__/csvZoneUpload.test.tsx.snap
tests/pages/__snapshots__/inputMethod.test.tsx.snap
tests/pages/api/csvUpload.test.ts
tests/pages/api/csvZoneUpload.test.ts

-   As per title, to allow users to upload MS excel created CSV files (xls and xlsx).
-   Use site, and upload xls or xlsx file.
-   [ ] chore - …

feat: allow users to upload xls and xlsx files

---

src/pages/api/describeSalesOfferPackage.ts
src/pages/selectSalesOfferPackage.tsx

-   To change the select SOP page so that the contents of the SOP can be seen, meaning the user can choose a description which means something to them, instead of just the contents.
-   Run site locally and use page
-   [ ] ci - Changes to our CI configuration files …

feat: Refactored page structure on how SOPs are displayed

---

server/index.ts
src/pages/createdFiles.tsx
tests/pages/createdFiles.test.tsx

-   Previously, scheme operators were seeing undefined as their created netex file names. They no longer show this.
-   Observe unit test which sets name. …

fix: scheme operators created netex page showing undefined

---

src/interfaces/index.ts
src/pages/createdFiles.tsx
tests/pages/__snapshots__/createdFiles.test.tsx.snap
tests/pages/createdFiles.test.tsx

-   This PR removes a field from the createdFiles page that displays the user's NOC when the NOC doesn't exist (i.e. when the user is a scheme operator) …

feat: removed undefined nocCode from createdFiles page

---

error/error/index.html

-   This PR fixes the styling on the static error page
-   Pull down this branch and run the site locally. Check the styling in the footer on `localhost:5555/error/index.html`. …

fix: styling on static error page

---

src/data/auroradb.ts
src/pages/api/csvZoneUpload.ts
tests/pages/api/csvZoneUpload.test.ts
tests/pages/returnDirection.test.tsx

-   Users were getting through to the end of their journey before finding out their ATCO/NaPTAN codes were incorrect. This change means they are checked immediately, and renders and error message on the page if they are.
-   Run site locally and attempt to upload a 
- …

fix: users will be told about incorrect ATCO/NaPTAN codes immediately

---

src/components/RadioConditionalInput.tsx
tests/components/RadioConditionalInput.test.tsx
tests/testData/mockData.ts

-   Adds input-type-specific checks for whether a default input value exists for conditional radio inputs. This now catches the case where a date input has no default, and therefore has a value of '##'.
-   Pull down this branch and navigate through the flat fare journey, up to the `/productDateInformation` page. Check that the conditional radio input is not expanded by default.
- …

fix: default checks added for different types of RadioConditionalInput

---

src/pages/api/csvUpload.ts
tests/testData/csvFareTriangleData.ts

-   Use papaparse skipEmtyLines to remove empty lines
-   Upload various csv and excel files to make sure they are all working as intended, with or without empty lines at the end of the file
-   [ ] ci - Changes to our CI configuration files and scripts (example …

Use papaparse skipEmtyLines to remove empty lines

---

src/pages/fareType.tsx
src/pages/noServices.tsx
src/pages/service.tsx
tests/pages/__snapshots__/noServices.test.tsx.snap
tests/pages/fareType.test.tsx
tests/pages/noServices.test.tsx
tests/pages/service.test.tsx

-   To have a page specifically for when the service page would error for there being no services found.
-   To test, go to the serverSideProps for the service.tsx page, and change the service array to an empty array, and it will redirect you there when you run it locally (single ticket).
-   [ ] build - Changes that affect the build system or external dependencies (example scopes: …

feat: Created new static page for no services

---

src/interfaces/index.ts
src/pages/api/register.ts
src/pages/confirmRegistration.tsx
tests/pages/__snapshots__/confirmRegistration.test.tsx.snap
tests/pages/api/register.test.ts
tests/pages/confirmRegistration.test.tsx

-   To warn users when they register if they do not have TNDS data set for their NOC codes.
-   Run site locally and create new user, copy the register link after the / and paste it after localhost:555 (e.g. http://localhost:5555/register?key=TrMrsuNosJJTWPL6) and fill out reg form. Main scenarios are with a NOC code that has TNDS (e.g. WBTR), with a NOC code which has no TNDS (e.g AAAAAAA), and with a multi-NOC code (e.g. WBTR|AAAAAA).
-   [ ] …

feat: warn users about lack of TNDS during registration

---

server/index.ts
src/pages/api/register.ts
src/pages/fareType.tsx
tests/pages/fareType.test.tsx

-   Fix bug preventing scheme operators from registering
-   Fix bug causing silent failure of user registration when no TNDS data exists for their NOC code
-   Run the site while authenticated under cfd-test profile
-   Create a user with a NOC code with no TNDS data (e.g. NATX)
-   Follow the registration link, replacing 'https://test.dft-cfd.infinityworks.com' with 'http://localhost:5555'
-   Clear cookies and refresh the page
-   Register and confirm that you are redirected to the /noServices page
-   Also confirm a Scheme Operator can register
-   [ ] refactor - A code …

Allow for registration of scheme operators and fix registration intercept

---

src/pages/api/periodValidity.ts
tests/pages/api/periodValidity.test.ts

-   Stopped issue occuring where end time is being incorrectly saved.
-   Run locally and try to recreate the bug.
-   [ ] chore - Other changes …

fix: stop persisting end time when not selected

---

src/pages/fareConfirmation.tsx
tests/pages/__snapshots__/fareConfirmation.test.tsx.snap
tests/pages/fareConfirmation.test.tsx

-   Adds a corresponding passengerType query string to the redirect when users choose to change the passenger type details on the fareConfirmation page
-   Run this branch locally
-   Ensure the 'change’ links for passenger type info fields redirect back to the /definePassengerType page with the correct query string parameter
-   [ ] build - Changes that affect the build system or …

fix: no passengerType query string on fareConfirmation redirect

---

src/interfaces/index.ts
src/interfaces/typeGuards.ts
src/pages/api/apiUtils/userData.ts
src/pages/api/productDateInformation.ts
src/pages/api/salesConfirmation.ts
src/pages/productDateInformation.tsx
src/pages/salesConfirmation.tsx
src/utils/sessions.ts
tests/pages/api/apiUtils/userData.test.ts
tests/pages/api/productDateInformation.test.ts
tests/pages/api/salesConfirmation.test.ts
tests/pages/createdFiles.test.tsx
tests/pages/salesConfirmation.test.tsx
tests/testData/mockData.ts

-   Fixes issue where product date inputs were not retained upon re-navigation to the productDateInformation page.
-   Run this branch locally and assure that the productDateInformation inputs are pre-populated with previous inputs when navigated back to.
-   [ ] ci - …

fix: product date info inputs not retained

---

src/pages/api/definePassengerType.ts
tests/pages/api/definePassengerType.test.ts

-   Prevents passenger type definitions (age ranges + proof documents) from being persisted when the user subsequently selects 'No' for each.
-   Test locally that age ranges and proof documents are not persisted when no is selected for their respective conditional radio inputs (check the fareConfirmation
-   [ ] build - Changes that affect the build system or external dependencies …

fix: passenger type definition persisted when no selected

---

.circleci/config.yml

-   As we are moving away from Selenium, we can stop the UI tests running in the pipeline until they are rewritten.
-   n/a
-   [ ] chore - Other …

fix: Removing ui tests being run as part of pipeline

---

package-lock.json
package.json
src/pages/service.tsx
src/pages/serviceList.tsx
tests/pages/__snapshots__/service.test.tsx.snap
tests/pages/__snapshots__/serviceList.test.tsx.snap

-   Toggles off the 'switch data source' button on the /service and /serviceList pages
-   Check the /service and /serviceList pages display correctly, with no switch data soruce button …

fix: toggle off switch data source button

---

src/data/auroradb.ts
src/interfaces/index.ts
src/pages/service.tsx
src/pages/serviceList.tsx
tests/pages/__snapshots__/service.test.tsx.snap
tests/pages/__snapshots__/serviceList.test.tsx.snap
tests/pages/service.test.tsx
tests/pages/serviceList.test.tsx

-   Adds origin and destination to the /service and /serviceList displays when BODS data source is chosen.
-   Switches back on the 'switch data source' button on these pages
-   Run the site locally. Check that services are displayed correctly on /service and /serviceList pages for BODS and TNDS data source.
-   [ ] build - Changes that affect the build system or external …

origin and destination added to service displays for bods data source

---

src/components/SwitchDataSource.tsx
src/constants/attributes.ts
src/data/auroradb.ts
src/pages/api/multipleOperatorsServiceList.ts
src/pages/api/switchDataSource.ts
src/pages/multipleOperatorsServiceList.tsx
src/pages/searchOperators.tsx
src/pages/service.tsx
src/pages/serviceList.tsx
src/utils/sessions.ts
tests/components/SwitchDataSource.test.tsx
tests/components/__snapshots__/SwitchDataSource.test.tsx.snap
tests/pages/__snapshots__/multipleOperatorsServiceList.test.tsx.snap
tests/pages/__snapshots__/service.test.tsx.snap
tests/pages/__snapshots__/serviceList.test.tsx.snap
tests/pages/api/multipleOperatorsServiceList.test.ts
tests/pages/multipleOperatorsServiceList.test.tsx
tests/pages/searchOperators.test.tsx
tests/pages/serviceList.test.tsx

-   To enable the user to switch the TXC data source from TNDS to BODS (and back) for the other operators as part of the multiple operator journey.
-   Run site locally and use multi operator multi service journey. Also use the serviceList afterwards / before for the flat fare journey to ensure no regressions across that.
-   [ ] build - Changes that affect the build system or …

feat: Multi operator TXC switch enabled

---

src/components/SwitchDataSource.tsx
src/pages/api/definePassengerType.ts
src/pages/api/switchDataSource.ts
src/pages/definePassengerType.tsx
tests/components/__snapshots__/SwitchDataSource.test.tsx.snap

-   Correcting a spelling mistake and making it so group passenger Anybody's cannot select a proof.
-   Run locally and test the group Anybody proof selection.
-   [ ] ci - Changes to our CI configuration files and scripts (example scopes: Travis, Circle, …

fix: data source spelling mistake and anybody treated as adult

---

cypress_tests/browserstack.json
package-lock.json
src/constants/attributes.ts
src/constants/index.ts
src/data/auroradb.ts
src/interfaces/index.ts
src/pages/api/apiUtils/index.ts
src/pages/api/definePassengerType.ts
src/pages/api/passengerType.ts
src/pages/passengerType.tsx
src/utils/sessions.ts
tests/pages/__snapshots__/passengerType.test.tsx.snap
tests/pages/api/definePassengerType.test.ts
tests/pages/api/passengerType.test.ts
tests/pages/passengerType.test.tsx

-   Reuse saved groups on the passenger types screen
-   Go through the single ticket journey, selecting to define a new group
-   Set all the group options and choose to name your new group when given the chance
-   Continue until you end up on the time restrictions page
-   Go back and start a new journey
-   This time select to reuse a saved group
-   Check you are taken direct to the time restrictions page
-   Complete the journey and check that the previous selected group configuration is used …

feat: CFD-245 Reusing groups
